#!/usr/bin/python
'''
Starts the targetcli CLI shell.

This file is part of targetcli.
Copyright (c) 2011-2013 by Datera, Inc

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
'''

import sys
from os import getuid
from targetcli import UIRoot
from rtslib import RTSLibError
from configshell import ConfigShell
from rtslib import __version__ as rtslib_version
from targetcli import __version__ as targetcli_version

class TargetCLI(ConfigShell):
    default_prefs = {'color_path': 'magenta',
                     'color_command': 'cyan',
                     'color_parameter': 'magenta',
                     'color_keyword': 'cyan',
                     'completions_in_columns': True,
                     'logfile': None,
                     'loglevel_console': 'info',
                     'loglevel_file': 'debug9',
                     'color_mode': True,
                     'prompt_length': 30,
                     'tree_max_depth': 0,
                     'tree_status_mode': True,
                     'tree_round_nodes': True,
                     'tree_show_root': True,
                     'auto_enable_tpgt': True,
                     'auto_add_mapped_luns': True,
                     'auto_cd_after_create': False,
                     'legacy_hba_view': False
                    }

def main():
    '''
    Start the targetcli shell.
    '''
    if getuid() == 0:
        is_root = True
    else:
        is_root = False

    shell = TargetCLI('~/.targetcli')
    if not is_root:
        shell.con.display("You are not root, disabling privileged commands.\n")

    root_node = UIRoot(shell, as_root=is_root)

    try:
        root_node.refresh()
    except RTSLibError, error:
        shell.con.display(shell.con.render_text(str(error), 'red'))

    if len(sys.argv) > 1:
        shell.run_cmdline(" ".join(sys.argv[1:]))
        sys.exit(0)

    shell.con.display("targetcli %s (rtslib %s)\n"
                      "Copyright (c) 2011-2013 by Datera, Inc.\n"
                      "All rights reserved."
                      % (targetcli_version, rtslib_version))
    shell.con.display('')
    shell.run_interactive()

if __name__ == "__main__":
    main()
